import { Adventure, AdventureDate, Booking, Operator } from "@/lib/types";

const standardItinerary = ["5:00 AM depart from pickup point", "8:00 AM reach base village", "9:00 AM trek briefing and start", "12:30 PM summit or waterfall time", "3:30 PM return to base", "7:30 PM arrive back in city"];
const standardIncluded = ["Certified local guide", "Breakfast", "First aid support", "Entry coordination"];
const standardCancellation = "48 hour refund window. Date transfer subject to slot availability.";

const baseAdventures: Adventure[] = [
  {
    id: "devkund-waterfall-trek",
    title: "Devkund Waterfall Trek",
    category: "Waterfalls",
    difficulty: "Beginner",
    basePrice: 1899,
    location: "Bhira, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: { Mumbai: 3.5, Pune: 4.5, Nashik: 6.5 },
    lat: 18.428,
    lng: 73.389,
    tags: ["Weekend Friendly", "Waterfall", "Forest Trail"],
    heroImage: "/images/devkund-waterfall-trek/1.jpg",
    gallery: ["/images/devkund-waterfall-trek/1.jpg", "/images/devkund-waterfall-trek/2.jpg", "/images/devkund-waterfall-trek/3.jpg", "/images/devkund-waterfall-trek/4.jpg"],
    description: "A forest-led waterfall trek designed for fast weekend decisions, with low technical complexity and strong monsoon appeal.",
    shortDescription: "High-confidence monsoon trek with easy entry and strong weekend value.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 10,
    operatorId: "op-west-1"
  },
  {
    id: "rajmachi-fort-trek",
    title: "Rajmachi Fort Trek",
    category: "Forts",
    difficulty: "Intermediate",
    basePrice: 2199,
    location: "Lonavala, Maharashtra",
    district: "Pune",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: { Mumbai: 2.75, Pune: 2.25, Nashik: 5.75 },
    lat: 18.829,
    lng: 73.388,
    tags: ["Fort", "Scenic", "Popular"],
    heroImage: "/images/rajmachi-fort-trek/1.jpg",
    gallery: ["/images/rajmachi-fort-trek/1.jpg", "/images/rajmachi-fort-trek/2.jpg", "/images/rajmachi-fort-trek/3.jpg", "/images/rajmachi-fort-trek/4.jpg"],
    description: "A heritage and hill experience that balances challenge, scenery, and travel efficiency.",
    shortDescription: "Iconic fort trek with moderate effort and excellent accessibility.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 11,
    operatorId: "op-fort-1"
  },
  {
    id: "kalsubai-sunrise-trek",
    title: "Kalsubai Sunrise Trek",
    category: "Trekking",
    difficulty: "Intermediate",
    basePrice: 2299,
    location: "Bari, Ahmednagar, Maharashtra",
    district: "Ahmednagar",
    originHints: ["Mumbai", "Nashik"],
    travelHoursFromOrigin: { Mumbai: 4.75, Pune: 5.5, Nashik: 3.25 },
    lat: 19.601,
    lng: 73.708,
    tags: ["Highest Peak", "Sunrise", "Ladders"],
    heroImage: "/images/kalsubai-sunrise-trek/1.jpg",
    gallery: ["/images/kalsubai-sunrise-trek/1.jpg", "/images/kalsubai-sunrise-trek/2.jpg", "/images/kalsubai-sunrise-trek/3.jpg", "/images/kalsubai-sunrise-trek/4.jpg"],
    description: "A Maharashtra bucket-list climb with a sunrise payoff and a clear challenge-to-reward story.",
    shortDescription: "Highest-peak badge value with strong payoff for fit weekend trekkers.",
    itinerary: ["11:30 PM depart from city", "3:30 AM reach Bari village", "4:00 AM trek start", "6:15 AM sunrise near summit", "8:30 AM breakfast and descent", "1:30 PM return to city"],
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 12,
    operatorId: "op-peak-1"
  },
  {
    id: "harihar-fort-climb",
    title: "Harihar Fort Climb",
    category: "Forts",
    difficulty: "Advanced",
    basePrice: 2599,
    location: "Trimbak, Nashik, Maharashtra",
    district: "Nashik",
    originHints: ["Nashik", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 4.5, Pune: 6.25, Nashik: 1.75 },
    lat: 19.886,
    lng: 73.469,
    tags: ["Rock Steps", "High Exposure", "Fort"],
    heroImage: "/images/harihar-fort-climb/1.jpg",
    gallery: ["/images/harihar-fort-climb/1.jpg", "/images/harihar-fort-climb/2.jpg", "/images/harihar-fort-climb/3.jpg", "/images/harihar-fort-climb/4.jpg"],
    description: "Steep carved steps and a high-drama ridgeline make Harihar a standout for advanced trekkers.",
    shortDescription: "A sharp, memorable climb for users seeking adrenaline and bragging rights.",
    itinerary: standardItinerary,
    included: ["Certified technical guide", "Breakfast", "First aid support", "Safety briefing"],
    cancellationPolicy: standardCancellation,
    durationHours: 10,
    operatorId: "op-nashik-1"
  },
  {
    id: "harishchandragad-kokankada",
    title: "Harishchandragad Trek",
    category: "Trekking",
    difficulty: "Advanced",
    basePrice: 2899,
    location: "Ahmednagar, Maharashtra",
    district: "Ahmednagar",
    originHints: ["Pune", "Nashik"],
    travelHoursFromOrigin: { Mumbai: 5.75, Pune: 4.5, Nashik: 4 },
    lat: 19.393,
    lng: 73.775,
    tags: ["Kokankada", "Long Trail", "Plateau"],
    heroImage: "/images/harishchandragad-kokankada/1.jpg",
    gallery: ["/images/harishchandragad-kokankada/1.jpg", "/images/harishchandragad-kokankada/2.jpg", "/images/harishchandragad-kokankada/3.jpg", "/images/harishchandragad-kokankada/4.jpg"],
    description: "A legendary ridge-and-cliff trek for experienced hikers willing to spend effort for one of the state's biggest views.",
    shortDescription: "Big-view weekend objective for advanced trekking groups.",
    itinerary: standardItinerary,
    included: ["Certified trek lead", "Breakfast", "First aid support", "Route coordination"],
    cancellationPolicy: standardCancellation,
    durationHours: 14,
    operatorId: "op-plateau-1"
  },
  {
    id: "lohagad-fort-trek",
    title: "Lohagad Fort Trek",
    category: "Forts",
    difficulty: "Beginner",
    basePrice: 1499,
    location: "Lonavala, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 2.5, Pune: 1.75, Nashik: 5.5 },
    lat: 18.711,
    lng: 73.48,
    tags: ["Beginner", "Fort", "Families"],
    heroImage: "/images/lohagad-fort-trek/1.jpg",
    gallery: ["/images/lohagad-fort-trek/1.jpg", "/images/lohagad-fort-trek/2.jpg", "/images/lohagad-fort-trek/3.jpg", "/images/lohagad-fort-trek/4.jpg"],
    description: "A forgiving fort climb with broad appeal, fast access, and a strong value story for first-time adventure users.",
    shortDescription: "Easy, affordable, and very demo-friendly for beginner recommendations.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 6,
    operatorId: "op-fort-1"
  },
  {
    id: "visapur-fort-trek",
    title: "Visapur Fort Trek",
    category: "Forts",
    difficulty: "Intermediate",
    basePrice: 1799,
    location: "Malavli, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 2.75, Pune: 2, Nashik: 5.75 },
    lat: 18.72,
    lng: 73.49,
    tags: ["Waterfall Route", "Fort", "Monsoon"],
    heroImage: "/images/visapur-fort-trek/1.jpg",
    gallery: ["/images/visapur-fort-trek/1.jpg", "/images/visapur-fort-trek/2.jpg", "/images/visapur-fort-trek/3.jpg", "/images/visapur-fort-trek/4.jpg"],
    description: "A broader, wetter monsoon fort trek that feels more adventurous than Lohagad while staying accessible.",
    shortDescription: "Popular rainy-season fort with solid thrill-to-effort balance.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 7,
    operatorId: "op-fort-1"
  },
  {
    id: "andharban-forest-trek",
    title: "Andharban Forest Trek",
    category: "Trekking",
    difficulty: "Intermediate",
    basePrice: 2099,
    location: "Tamhini, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 4.5, Pune: 2.5, Nashik: 7 },
    lat: 18.4,
    lng: 73.42,
    tags: ["Dense Forest", "Monsoon", "Long Walk"],
    heroImage: "/images/andharban-forest-trek/1.jpg",
    gallery: ["/images/andharban-forest-trek/1.jpg", "/images/andharban-forest-trek/2.jpg", "/images/andharban-forest-trek/3.jpg", "/images/andharban-forest-trek/4.jpg"],
    description: "A shaded monsoon trail through thick forest canopy, ideal for users who prioritize immersion over summit bragging rights.",
    shortDescription: "A lush weekend escape with strong weather and scenery appeal.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 11,
    operatorId: "op-forest-1"
  },
  {
    id: "pawna-lake-camping",
    title: "Pawna Lake Camping",
    category: "Camping",
    difficulty: "Beginner",
    basePrice: 1399,
    location: "Pawna, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 2.75, Pune: 1.75, Nashik: 6 },
    lat: 18.651,
    lng: 73.49,
    tags: ["Camping", "Group Friendly", "Easy"],
    heroImage: "/images/pawna-lake-camping/1.jpg",
    gallery: ["/images/pawna-lake-camping/1.jpg", "/images/pawna-lake-camping/2.jpg", "/images/pawna-lake-camping/3.jpg", "/images/pawna-lake-camping/4.jpg"],
    description: "Low-friction lake camping for users optimizing for affordability, friends, and minimal planning risk.",
    shortDescription: "Budget-friendly overnight with very high beginner confidence.",
    itinerary: ["4:00 PM check-in at campsite", "5:30 PM lakeside activities", "8:00 PM dinner", "10:00 PM bonfire", "7:30 AM breakfast", "10:00 AM check-out"],
    included: ["Tent stay", "Dinner", "Breakfast", "Campsite host"],
    cancellationPolicy: standardCancellation,
    durationHours: 15,
    operatorId: "op-camp-1"
  },
  {
    id: "sandhan-valley-canyoning",
    title: "Sandhan Valley Canyoning",
    category: "Trekking",
    difficulty: "Advanced",
    basePrice: 3299,
    location: "Samrad, Ahmednagar, Maharashtra",
    district: "Ahmednagar",
    originHints: ["Nashik", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 5.5, Pune: 6.25, Nashik: 3.5 },
    lat: 19.52,
    lng: 73.69,
    tags: ["Canyon", "Rappelling", "Technical"],
    heroImage: "/images/sandhan-valley-canyoning/1.jpg",
    gallery: ["/images/sandhan-valley-canyoning/1.jpg", "/images/sandhan-valley-canyoning/2.jpg", "/images/sandhan-valley-canyoning/3.jpg", "/images/sandhan-valley-canyoning/4.jpg"],
    description: "Technical canyon terrain for advanced users who want maximum adventure intensity in a single weekend.",
    shortDescription: "Premium, technical, and memorable for experienced groups.",
    itinerary: standardItinerary,
    included: ["Technical guide", "Rappelling setup", "Breakfast", "First aid support"],
    cancellationPolicy: standardCancellation,
    durationHours: 14,
    operatorId: "op-plateau-1"
  },
  {
    id: "kolad-river-kayaking",
    title: "Kolad River Kayaking",
    category: "Water Sports",
    difficulty: "Intermediate",
    basePrice: 2499,
    location: "Kolad, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 3, Pune: 2.5, Nashik: 6 },
    lat: 18.403,
    lng: 73.223,
    tags: ["Rapids", "Guided", "Fast Thrill"],
    heroImage: "/images/kolad-river-kayaking/1.jpg",
    gallery: ["/images/kolad-river-kayaking/1.jpg", "/images/kolad-river-kayaking/2.jpg", "/images/kolad-river-kayaking/3.jpg", "/images/kolad-river-kayaking/4.jpg"],
    description: "Guided kayaking for users who want a sharper thrill without committing their whole weekend.",
    shortDescription: "Fast, energetic river session with compact travel from Pune.",
    itinerary: ["6:00 AM depart", "9:00 AM reach Kolad", "9:30 AM safety briefing", "10:00 AM kayaking session", "1:00 PM lunch break", "5:30 PM return"],
    included: ["Certified water guide", "Kayak and safety gear", "Breakfast", "First aid support"],
    cancellationPolicy: standardCancellation,
    durationHours: 8,
    operatorId: "op-river-1"
  },
  {
    id: "bhandardara-lakeside-camp",
    title: "Bhandardara Lakeside Camp",
    category: "Camping",
    difficulty: "Beginner",
    basePrice: 1599,
    location: "Bhandardara, Ahmednagar, Maharashtra",
    district: "Ahmednagar",
    originHints: ["Mumbai", "Nashik"],
    travelHoursFromOrigin: { Mumbai: 4, Pune: 4.75, Nashik: 2.75 },
    lat: 19.533,
    lng: 73.756,
    tags: ["Camping", "Stargazing", "Relaxed"],
    heroImage: "/images/bhandardara-lakeside-camp/1.jpg",
    gallery: ["/images/bhandardara-lakeside-camp/1.jpg", "/images/bhandardara-lakeside-camp/2.jpg", "/images/bhandardara-lakeside-camp/3.jpg", "/images/bhandardara-lakeside-camp/4.jpg"],
    description: "Low-friction camping for users who want a scenic outdoor night without technical challenge.",
    shortDescription: "Relaxed overnight that balances price, scenery, and group appeal.",
    itinerary: ["4:00 PM check-in", "5:30 PM lake walk", "8:00 PM dinner", "10:00 PM stargazing", "8:00 AM breakfast", "10:00 AM check-out"],
    included: ["Tent stay", "Dinner", "Breakfast", "Campsite host"],
    cancellationPolicy: standardCancellation,
    durationHours: 16,
    operatorId: "op-camp-1"
  },
  {
    id: "sula-glamp-retreat",
    title: "Sula Glamp Retreat",
    category: "Glamping",
    difficulty: "Beginner",
    basePrice: 3499,
    location: "Nashik, Maharashtra",
    district: "Nashik",
    originHints: ["Nashik", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 4.5, Pune: 5.5, Nashik: 0.75 },
    lat: 20.005,
    lng: 73.79,
    tags: ["Premium", "Scenic", "Comfort First"],
    heroImage: "/images/sula-glamp-retreat/1.jpg",
    gallery: ["/images/sula-glamp-retreat/1.jpg", "/images/sula-glamp-retreat/2.jpg", "/images/sula-glamp-retreat/3.jpg", "/images/sula-glamp-retreat/4.jpg"],
    description: "A premium outdoor stay for users who care more about confidence and comfort than exertion.",
    shortDescription: "Luxury-led weekend pick with low effort and high comfort.",
    itinerary: ["2:00 PM check-in", "4:30 PM vineyard walk", "7:30 PM dinner", "8:30 AM breakfast", "10:00 AM leisure time", "12:00 PM check-out"],
    included: ["Glamp stay", "Breakfast", "Property host", "Activity coordination"],
    cancellationPolicy: standardCancellation,
    durationHours: 18,
    operatorId: "op-glamp-1"
  },
  {
    id: "matheran-horseback-trail",
    title: "Matheran Horseback Trail",
    category: "Trekking",
    difficulty: "Beginner",
    basePrice: 1699,
    location: "Matheran, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: { Mumbai: 2.5, Pune: 3.75, Nashik: 5.75 },
    lat: 18.988,
    lng: 73.271,
    tags: ["Scenic", "Family Friendly", "Easy"],
    heroImage: "/images/matheran-horseback-trail/1.jpg",
    gallery: ["/images/matheran-horseback-trail/1.jpg", "/images/matheran-horseback-trail/2.jpg", "/images/matheran-horseback-trail/3.jpg", "/images/matheran-horseback-trail/4.jpg"],
    description: "A softer outdoor pick for users who want scenery, comfort, and low decision friction over raw difficulty.",
    shortDescription: "A gentle outdoor escape with broad premium-consumer appeal.",
    itinerary: standardItinerary,
    included: standardIncluded,
    cancellationPolicy: standardCancellation,
    durationHours: 7,
    operatorId: "op-west-1"
  },
  {
    id: "alibaug-coastal-kayak",
    title: "Alibaug Coastal Kayak",
    category: "Water Sports",
    difficulty: "Beginner",
    basePrice: 1999,
    location: "Alibaug, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: { Mumbai: 2.25, Pune: 3.75, Nashik: 6.25 },
    lat: 18.641,
    lng: 72.872,
    tags: ["Coast", "Paddling", "Easy Adventure"],
    heroImage: "/images/alibaug-coastal-kayak/1.jpg",
    gallery: ["/images/alibaug-coastal-kayak/1.jpg", "/images/alibaug-coastal-kayak/2.jpg", "/images/alibaug-coastal-kayak/3.jpg", "/images/alibaug-coastal-kayak/4.jpg"],
    description: "A lower-risk paddle experience for users who want something outdoorsy, photogenic, and easy to commit to.",
    shortDescription: "Low-effort coastal adventure that feels distinct from trekking-heavy alternatives.",
    itinerary: ["6:30 AM depart", "9:00 AM reach Alibaug", "9:30 AM safety briefing", "10:00 AM coastal kayaking", "12:30 PM breakfast break", "4:30 PM return"],
    included: ["Certified water guide", "Kayak and safety gear", "Breakfast", "First aid support"],
    cancellationPolicy: standardCancellation,
    durationHours: 6,
    operatorId: "op-river-1"
  },
  {
    id: "torna-fort-trek",
    title: "Torna Fort Trek",
    category: "Forts",
    difficulty: "Advanced",
    basePrice: 2699,
    location: "Velhe, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: { Mumbai: 4.75, Pune: 2.25, Nashik: 7 },
    lat: 18.276,
    lng: 73.622,
    tags: ["Historic", "Long Climb", "Windy Ridge"],
    heroImage: "/images/torna-fort-trek/1.jpg",
    gallery: ["/images/torna-fort-trek/1.jpg", "/images/torna-fort-trek/2.jpg", "/images/torna-fort-trek/3.jpg", "/images/torna-fort-trek/4.jpg"],
    description: "A demanding fort climb with strong historic identity and a more serious effort profile for seasoned trekkers.",
    shortDescription: "Big-effort fort objective for high-intent trekkers from Pune.",
    itinerary: standardItinerary,
    included: ["Certified trek lead", "Breakfast", "First aid support", "Route coordination"],
    cancellationPolicy: standardCancellation,
    durationHours: 13,
    operatorId: "op-peak-1"
  },
  {
    id: "sinhagad-fort-trek",
    title: "Sinhagad Fort Trek",
    category: "Forts",
    difficulty: "Beginner",
    basePrice: 1299,
    location: "Sinhagad, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 4, "Nashik": 6, "Pune": 1},
    lat: 18.3664,
    lng: 73.7556,
    tags: ["Fort", "Beginner", "Sunrise Views", "Historical"],
    heroImage: "/images/sinhagad-fort-trek/1.jpg",
    gallery: ["/images/sinhagad-fort-trek/1.jpg", "/images/sinhagad-fort-trek/2.jpg", "/images/sinhagad-fort-trek/3.jpg", "/images/sinhagad-fort-trek/4.jpg"],
    description: "Sinhagad Fort, also known as Lion's Fort, stands majestically at 1,312 meters and played a crucial role in Maratha history. The trek offers panoramic views of the Sahyadri ranges and the twin villages of Sinhagad below. Perfect for beginners seeking a blend of history, adventure, and breathtaking landscapes.",
    shortDescription: "Historic Maratha fort trek with stunning valley views, ideal for first-time trekkers.",
    itinerary: ["5:00 AM - Depart from Pune", "6:30 AM - Arrive at base village", "7:00 AM - Trek start from Sinhagad village", "9:30 AM - Reach fort summit", "10:00 AM - Breakfast and exploration", "12:00 PM - Begin descent", "2:00 PM - Return to base", "3:30 PM - Arrive back in Pune"],
    included: ["Certified local guide", "Breakfast at summit", "First aid support", "Entry coordination", "Transport from meeting point"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 8,
    operatorId: "op-fort-1"
  },
  {
    id: "rajgad-fort-trek",
    title: "Rajgad Fort Trek",
    category: "Forts",
    difficulty: "Advanced",
    basePrice: 2699,
    location: "Rajgad, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 5, "Nashik": 7, "Pune": 2},
    lat: 18.2444,
    lng: 73.6797,
    tags: ["Fort", "Advanced", "Shivaji's Capital", "Multi-Peak", "Camping"],
    heroImage: "/images/rajgad-fort-trek/1.jpg",
    gallery: ["/images/rajgad-fort-trek/1.jpg", "/images/rajgad-fort-trek/2.jpg", "/images/rajgad-fort-trek/3.jpg", "/images/rajgad-fort-trek/4.jpg"],
    description: "Rajgad, meaning King's Fort, served as Chhatrapati Shivaji Maharaj's capital for 26 years and remains one of Maharashtra's most challenging treks. The fort features three distinctive peaks—Suvela Machi, Padmavati Machi, and Sanjivani Machi—connected by ancient stone pathways. This demanding trek rewards adventurers with unparalleled historical significance and 360-degree Sahyadri vistas.",
    shortDescription: "Chhatrapati Shivaji's former capital, a challenging multi-peak fort trek for experienced hikers.",
    itinerary: ["4:00 AM - Depart from Pune", "6:30 AM - Reach Gunjavane village base", "7:00 AM - Trek begins", "11:00 AM - Summit Suvela Machi", "12:00 PM - Lunch break", "1:00 PM - Explore Padmavati and Sanjivani Machi", "3:30 PM - Begin descent", "6:00 PM - Return to base", "8:30 PM - Arrive back in Pune"],
    included: ["Expert trekking guide", "Breakfast and lunch", "First aid kit", "Entry fees", "Transport from Pune"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 14,
    operatorId: "op-fort-1"
  },
  {
    id: "raigad-fort-trek",
    title: "Raigad Fort Trek",
    category: "Forts",
    difficulty: "Intermediate",
    basePrice: 1899,
    location: "Raigad, Raigad District, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 7, "Pune": 4},
    lat: 18.2356,
    lng: 73.4397,
    tags: ["Fort", "Intermediate", "Coronation Site", "Ropeway Option", "Heritage"],
    heroImage: "/images/raigad-fort-trek/1.jpg",
    gallery: ["/images/raigad-fort-trek/1.jpg", "/images/raigad-fort-trek/2.jpg", "/images/raigad-fort-trek/3.jpg", "/images/raigad-fort-trek/4.jpg"],
    description: "Raigad Fort holds immense historical importance as the site where Shivaji Maharaj was crowned Chhatrapati in 1674. The trek ascends 1,400 stone steps through dense forest to reveal royal chambers, audience halls, and the iconic Maha Darwaza gateway. This intermediate trek combines physical challenge with profound cultural heritage.",
    shortDescription: "The coronation fort of Chhatrapati Shivaji, accessible via historic stone stairway or ropeway.",
    itinerary: ["5:30 AM - Depart from Mumbai/Pune", "8:30 AM - Reach Raigad base", "9:00 AM - Begin ascent via stone steps", "11:30 AM - Summit arrival", "12:00 PM - Guided tour of palace ruins", "1:00 PM - Lunch break", "2:30 PM - Descent begins", "4:30 PM - Base arrival", "7:30 PM - Return to origin city"],
    included: ["Experienced guide", "Entry and parking fees", "Lunch", "First aid support", "Round-trip transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 12,
    operatorId: "op-fort-1"
  },
  {
    id: "tikona-fort-trek",
    title: "Tikona Fort Trek",
    category: "Forts",
    difficulty: "Beginner",
    basePrice: 1199,
    location: "Tikona, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai", "Lonavala"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 5, "Pune": 2},
    lat: 18.6389,
    lng: 73.5008,
    tags: ["Fort", "Beginner", "Triangle Shape", "Lake Views", "Weekend Trek"],
    heroImage: "/images/tikona-fort-trek/1.jpg",
    gallery: ["/images/tikona-fort-trek/1.jpg", "/images/tikona-fort-trek/2.jpg", "/images/tikona-fort-trek/3.jpg", "/images/tikona-fort-trek/4.jpg"],
    description: "Tikona Fort, named for its distinctive triangular shape, sits at 1,077 meters overlooking Pawna Lake and the Lonavala valley. The well-marked trail makes it perfect for beginner trekkers while still offering rewarding views of the Western Ghats. The fort's strategic architecture and lakeside location create a picturesque trekking experience.",
    shortDescription: "Easy triangle-shaped fort trek with spectacular Pawna Lake views, ideal for families.",
    itinerary: ["6:00 AM - Depart from Pune", "8:00 AM - Arrive at Tikona village", "8:30 AM - Trek start", "10:30 AM - Reach summit", "11:00 AM - Explore fort and breakfast", "1:00 PM - Descent begins", "2:30 PM - Base arrival", "4:30 PM - Return to Pune"],
    included: ["Local guide", "Breakfast", "First aid kit", "Entry fees", "Transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 9,
    operatorId: "op-west-1"
  },
  {
    id: "korigad-fort-trek",
    title: "Korigad Fort Trek",
    category: "Forts",
    difficulty: "Beginner",
    basePrice: 1399,
    location: "Korigad, Lonavala, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai", "Lonavala"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 5, "Pune": 2},
    lat: 18.7753,
    lng: 73.4661,
    tags: ["Fort", "Beginner", "Monsoon Trek", "Lake Views", "Ancient Caves"],
    heroImage: "/images/korigad-fort-trek/1.jpg",
    gallery: ["/images/korigad-fort-trek/1.jpg", "/images/korigad-fort-trek/2.jpg", "/images/korigad-fort-trek/3.jpg", "/images/korigad-fort-trek/4.jpg"],
    description: "Korigad Fort near Lonavala offers an accessible trek through scenic monsoon landscapes with views of Aamby Valley and Pawna Dam. The fort features ancient water cisterns, carved caves, and the small Korai Devi temple at its summit. Its gradual ascent and proximity to popular hill stations make it ideal for weekend adventurers and families.",
    shortDescription: "Gentle monsoon trek near Lonavala with ancient caves and valley panoramas.",
    itinerary: ["6:30 AM - Depart from Pune/Mumbai", "8:30 AM - Reach Peth Shahpur base", "9:00 AM - Trek begins", "11:00 AM - Summit arrival", "11:30 AM - Explore fort and caves", "12:30 PM - Breakfast break", "2:00 PM - Descend", "3:30 PM - Base return", "5:30 PM - Arrive back"],
    included: ["Certified guide", "Breakfast", "Entry fees", "First aid support", "Round-trip transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 10,
    operatorId: "op-west-1"
  },
  {
    id: "kalavantin-durg-trek",
    title: "Kalavantin Durg Trek",
    category: "Forts",
    difficulty: "Advanced",
    basePrice: 2899,
    location: "Kalavantin Durg, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 7, "Pune": 4},
    lat: 18.8869,
    lng: 73.2569,
    tags: ["Fort", "Advanced", "Rock Climbing", "Steep Stairs", "Adrenaline", "Expert Only"],
    heroImage: "/images/kalavantin-durg-trek/1.jpg",
    gallery: ["/images/kalavantin-durg-trek/1.jpg", "/images/kalavantin-durg-trek/2.jpg", "/images/kalavantin-durg-trek/3.jpg", "/images/kalavantin-durg-trek/4.jpg"],
    description: "Kalavantin Durg, also called Prabalgad, is legendary for its near-vertical rock-cut staircase carved into the mountain face at dizzying heights. This pinnacle requires courage, fitness, and a head for heights as trekkers navigate sheer drops on exposed stone steps. Only for the most adventurous seeking an adrenaline-fueled challenge with unmatched aerial views of the Sahyadris.",
    shortDescription: "Extreme vertical rock-cut stairs for fearless trekkers seeking the ultimate adrenaline rush.",
    itinerary: ["4:30 AM - Depart from Mumbai/Pune", "7:30 AM - Thakurwadi base village", "8:00 AM - Trek to Prabalgad begins", "10:30 AM - Reach Prabalgad plateau", "11:00 AM - Ascend Kalavantin rock stairs", "12:00 PM - Summit pinnacle", "12:30 PM - Lunch and rest", "2:00 PM - Careful descent", "5:00 PM - Base return", "8:00 PM - Arrive back"],
    included: ["Expert climbing guide", "Safety gear and harness", "Breakfast and lunch", "First aid and rescue kit", "Transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 13,
    operatorId: "op-peak-1"
  },
  {
    id: "karnala-fort-trek",
    title: "Karnala Fort Trek",
    category: "Forts",
    difficulty: "Beginner",
    basePrice: 1249,
    location: "Karnala, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Navi Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 2, "Nashik": 6, "Pune": 4},
    lat: 18.8833,
    lng: 73.1167,
    tags: ["Fort", "Beginner", "Bird Sanctuary", "Nature Trail", "Family Friendly"],
    heroImage: "/images/karnala-fort-trek/1.jpg",
    gallery: ["/images/karnala-fort-trek/1.jpg", "/images/karnala-fort-trek/2.jpg", "/images/karnala-fort-trek/3.jpg", "/images/karnala-fort-trek/4.jpg"],
    description: "Karnala Fort sits within the biodiverse Karnala Bird Sanctuary, offering trekkers a unique blend of history and ornithology. The gentle forested trail winds through habitat home to over 150 bird species before reaching the fort's distinctive thumb-shaped basalt pinnacle. Perfect for nature enthusiasts and families seeking an easy weekend escape from Mumbai.",
    shortDescription: "Easy nature trek through a bird sanctuary to a historic fort, ideal for Mumbai day trips.",
    itinerary: ["7:00 AM - Depart from Mumbai", "9:00 AM - Karnala Bird Sanctuary entrance", "9:30 AM - Trek begins", "11:30 AM - Fort base arrival", "12:00 PM - Explore fort and pinnacle viewpoint", "1:00 PM - Packed lunch", "2:30 PM - Descent through sanctuary", "4:00 PM - Exit sanctuary", "6:00 PM - Return to Mumbai"],
    included: ["Naturalist guide", "Sanctuary entry fees", "Packed lunch", "Bird watching tips", "Transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 10,
    operatorId: "op-west-1"
  },
  {
    id: "irshalgad-fort-trek",
    title: "Irshalgad Fort Trek",
    category: "Forts",
    difficulty: "Intermediate",
    basePrice: 1999,
    location: "Irshalgad, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune", "Panvel"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 7, "Pune": 4},
    lat: 18.9667,
    lng: 73.2833,
    tags: ["Fort", "Intermediate", "Monsoon Beauty", "Cave Temple", "Off-Beat"],
    heroImage: "/images/irshalgad-fort-trek/1.jpg",
    gallery: ["/images/irshalgad-fort-trek/1.jpg", "/images/irshalgad-fort-trek/2.jpg", "/images/irshalgad-fort-trek/3.jpg", "/images/irshalgad-fort-trek/4.jpg"],
    description: "Irshalgad Fort, perched at 1,200 meters, offers an off-the-beaten-path intermediate trek through lush monsoon greenery and rock patches. The summit plateau features ancient water tanks, caves, and a small temple, with commanding views of Matheran, Prabalgad, and the Konkan coastline. This hidden gem rewards trekkers with solitude and pristine natural beauty.",
    shortDescription: "Scenic intermediate trek to a lesser-known fort with caves, temple ruins, and coastal views.",
    itinerary: ["5:30 AM - Depart from Mumbai/Pune", "8:00 AM - Irshalwadi base village", "8:30 AM - Trek start", "11:30 AM - Summit plateau", "12:00 PM - Explore caves and temple", "1:00 PM - Lunch break", "2:30 PM - Begin descent", "5:00 PM - Base village", "7:30 PM - Return to origin"],
    included: ["Experienced guide", "Breakfast and lunch", "Entry coordination", "First aid kit", "Round-trip transport"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 12,
    operatorId: "op-plateau-1"
  },
  {
    id: "tamhini-waterfall-trek",
    title: "Tamhini Waterfall Trek",
    category: "Waterfalls",
    difficulty: "Beginner",
    basePrice: 1599,
    location: "Tamhini Ghat, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 4, "Nashik": 6, "Pune": 2},
    lat: 18.474,
    lng: 73.384,
    tags: ["Waterfall", "Monsoon", "Scenic"],
    heroImage: "/images/tamhini-waterfall-trek/1.jpg",
    gallery: ["/images/tamhini-waterfall-trek/1.jpg", "/images/tamhini-waterfall-trek/2.jpg", "/images/tamhini-waterfall-trek/3.jpg", "/images/tamhini-waterfall-trek/4.jpg"],
    description: "Tamhini Ghat transforms into a cascading wonderland during monsoons with dozens of waterfalls flowing down verdant hillsides. The scenic drive and easy trails make this an ideal family-friendly adventure. Witness the Sahyadri mountains at their most dramatic with misty valleys and roaring streams.",
    shortDescription: "Explore dozens of monsoon waterfalls along the scenic Tamhini Ghat route.",
    itinerary: ["5:00 AM - Depart from meeting point", "7:30 AM - Arrive at Tamhini base, breakfast", "8:30 AM - Begin waterfall trail exploration", "12:00 PM - Main waterfall photography session", "1:00 PM - Picnic lunch by the stream", "3:00 PM - Return trek begins", "6:30 PM - Arrive back at origin"],
    included: ["Certified local guide", "Breakfast and lunch", "First aid support", "Entry coordination"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 9,
    operatorId: "op-forest-1"
  },
  {
    id: "naneghat-trek",
    title: "Naneghat Trek",
    category: "Trekking",
    difficulty: "Intermediate",
    basePrice: 1899,
    location: "Naneghat, Junnar, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 5, "Nashik": 4, "Pune": 3},
    lat: 19.365,
    lng: 73.721,
    tags: ["Historical", "Mountain Pass", "Ancient Route"],
    heroImage: "/images/naneghat-trek/1.jpg",
    gallery: ["/images/naneghat-trek/1.jpg", "/images/naneghat-trek/2.jpg", "/images/naneghat-trek/3.jpg", "/images/naneghat-trek/4.jpg"],
    description: "Naneghat is an ancient mountain pass with 2nd century BCE inscriptions carved into the rock. The moderate trek rewards you with panoramic Sahyadri views and a glimpse into historic trade routes. Rich biodiversity and archaeological significance make this a unique cultural-nature experience.",
    shortDescription: "Trek the ancient mountain pass with 2000-year-old rock inscriptions.",
    itinerary: ["5:30 AM - Depart from meeting point", "8:30 AM - Reach Vaishakhare village base", "9:00 AM - Begin ascent to Naneghat pass", "11:30 AM - Summit reach, explore inscriptions", "1:00 PM - Lunch at plateau", "2:30 PM - Descent begins", "6:00 PM - Return to origin"],
    included: ["Expert trek leader", "Trail breakfast and lunch", "First aid kit", "Historical site guide"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 10,
    operatorId: "op-plateau-1"
  },
  {
    id: "malshej-ghat-trek",
    title: "Malshej Ghat Trek",
    category: "Trekking",
    difficulty: "Beginner",
    basePrice: 1499,
    location: "Malshej Ghat, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 4.5, "Nashik": 5, "Pune": 3.5},
    lat: 19.331,
    lng: 73.673,
    tags: ["Monsoon", "Flamingos", "Hill Station"],
    heroImage: "/images/malshej-ghat-trek/1.jpg",
    gallery: ["/images/malshej-ghat-trek/1.jpg", "/images/malshej-ghat-trek/2.jpg", "/images/malshej-ghat-trek/3.jpg", "/images/malshej-ghat-trek/4.jpg"],
    description: "Malshej Ghat is famous for its monsoon waterfalls, flamingo migration, and cloud-kissed peaks. The easy trail winds through lush greenery with stunning viewpoints at every turn. Perfect for beginners seeking Sahyadri beauty without strenuous climbs.",
    shortDescription: "Beginner-friendly trek through misty peaks and seasonal waterfalls.",
    itinerary: ["6:00 AM - Depart from meeting point", "9:30 AM - Arrive Malshej, light refreshments", "10:00 AM - Begin plateau trek", "12:30 PM - Reach viewpoint, photography break", "1:30 PM - Lunch by the falls", "3:00 PM - Return trek", "6:30 PM - Back to origin"],
    included: ["Trekking guide", "Breakfast and packed lunch", "First aid kit", "Transport coordination"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 8,
    operatorId: "op-west-1"
  },
  {
    id: "mulshi-lake-camping",
    title: "Mulshi Lake Camping",
    category: "Camping",
    difficulty: "Beginner",
    basePrice: 2199,
    location: "Mulshi Lake, Pune, Maharashtra",
    district: "Pune",
    originHints: ["Pune", "Mumbai"],
    travelHoursFromOrigin: {"Mumbai": 4, "Nashik": 6, "Pune": 1.5},
    lat: 18.521,
    lng: 73.495,
    tags: ["Lakeside", "Camping", "Stargazing"],
    heroImage: "/images/mulshi-lake-camping/1.jpg",
    gallery: ["/images/mulshi-lake-camping/1.jpg", "/images/mulshi-lake-camping/2.jpg", "/images/mulshi-lake-camping/3.jpg", "/images/mulshi-lake-camping/4.jpg"],
    description: "Camp by the serene Mulshi Lake surrounded by verdant hills and tranquil waters. Enjoy bonfire nights, stargazing, and kayaking in one of Pune's most picturesque camping destinations. Wake up to misty mornings and the sound of birdsong.",
    shortDescription: "Overnight lakeside camping with bonfire, stargazing, and water activities.",
    itinerary: ["3:00 PM - Arrival at Mulshi campsite", "4:00 PM - Tent setup and orientation", "5:00 PM - Kayaking and lakeside activities", "7:00 PM - Bonfire and BBQ dinner", "9:00 PM - Stargazing session", "7:00 AM - Morning tea and breakfast", "11:00 AM - Pack up and departure"],
    included: ["Camping tents and gear", "Dinner, breakfast", "Bonfire setup", "Kayaking equipment", "Safety supervision"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 20,
    operatorId: "op-camp-1"
  },
  {
    id: "bhivpuri-waterfall-rappelling",
    title: "Bhivpuri Waterfall Rappelling",
    category: "Waterfalls",
    difficulty: "Intermediate",
    basePrice: 2299,
    location: "Bhivpuri, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 2.5, "Nashik": 6, "Pune": 3.5},
    lat: 18.983,
    lng: 73.429,
    tags: ["Waterfall", "Rappelling", "Adventure Sports"],
    heroImage: "/images/bhivpuri-waterfall-rappelling/1.jpg",
    gallery: ["/images/bhivpuri-waterfall-rappelling/1.jpg", "/images/bhivpuri-waterfall-rappelling/2.jpg", "/images/bhivpuri-waterfall-rappelling/3.jpg", "/images/bhivpuri-waterfall-rappelling/4.jpg"],
    description: "Descend a 150-foot cascading waterfall with professional rappelling gear and expert instructors. Bhivpuri offers an adrenaline rush combined with stunning natural beauty during the monsoon season. No prior rappelling experience required—full training provided.",
    shortDescription: "Rappel down a 150-foot monsoon waterfall with expert guidance.",
    itinerary: ["6:00 AM - Depart from meeting point", "8:30 AM - Reach Bhivpuri base", "9:00 AM - Safety briefing and gear fitting", "10:00 AM - Rappelling training session", "11:00 AM - Begin waterfall rappelling", "1:00 PM - Lunch break", "3:00 PM - Return journey begins", "5:30 PM - Back to origin"],
    included: ["Professional rappelling gear", "Certified instructors", "Safety equipment", "Breakfast and lunch", "First aid"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 9,
    operatorId: "op-river-1"
  },
  {
    id: "kondana-caves-trek",
    title: "Kondana Caves Trek",
    category: "Trekking",
    difficulty: "Beginner",
    basePrice: 1399,
    location: "Kondana Caves, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 6.5, "Pune": 3},
    lat: 18.878,
    lng: 73.389,
    tags: ["Historical", "Buddhist Caves", "Monsoon"],
    heroImage: "/images/kondana-caves-trek/1.jpg",
    gallery: ["/images/kondana-caves-trek/1.jpg", "/images/kondana-caves-trek/2.jpg", "/images/kondana-caves-trek/3.jpg", "/images/kondana-caves-trek/4.jpg"],
    description: "Discover ancient Buddhist caves dating back to 1st century BCE nestled in lush monsoon greenery. The easy trek passes through verdant forests and waterfalls before reaching the rock-cut caves with intricate carvings. A perfect blend of history, nature, and spirituality.",
    shortDescription: "Explore 2000-year-old Buddhist caves amid monsoon waterfalls.",
    itinerary: ["6:00 AM - Depart from meeting point", "9:00 AM - Arrive at Kondivade village base", "9:30 AM - Begin forest trail trek", "11:00 AM - Reach Kondana Caves, guided tour", "1:00 PM - Lunch near caves", "2:30 PM - Return trek via waterfall route", "5:30 PM - Back to origin"],
    included: ["Heritage guide", "Breakfast and lunch", "First aid support", "Cave entry coordination"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 8,
    operatorId: "op-forest-1"
  },
  {
    id: "garbett-plateau-trek",
    title: "Garbett Plateau Trek",
    category: "Trekking",
    difficulty: "Advanced",
    basePrice: 2499,
    location: "Garbett Plateau, Raigad, Maharashtra",
    district: "Raigad",
    originHints: ["Mumbai", "Pune"],
    travelHoursFromOrigin: {"Mumbai": 3, "Nashik": 6.5, "Pune": 4},
    lat: 18.988,
    lng: 73.378,
    tags: ["Plateau", "Advanced", "Scenic Views"],
    heroImage: "/images/garbett-plateau-trek/1.jpg",
    gallery: ["/images/garbett-plateau-trek/1.jpg", "/images/garbett-plateau-trek/2.jpg", "/images/garbett-plateau-trek/3.jpg", "/images/garbett-plateau-trek/4.jpg"],
    description: "Challenge yourself with this steep ascent to the spectacular Garbett Plateau offering 360-degree Sahyadri vistas. The advanced trail features rock patches, dense forests, and dramatic cliff edges. Monsoon clouds swirling around the plateau create an ethereal experience.",
    shortDescription: "Advanced trek to a dramatic plateau with panoramic mountain views.",
    itinerary: ["5:00 AM - Depart from meeting point", "7:30 AM - Reach Diksal village base", "8:00 AM - Begin steep ascent", "11:00 AM - Summit Garbett Plateau", "12:00 PM - Explore plateau, photography", "1:30 PM - Lunch at plateau", "3:00 PM - Descent begins", "6:30 PM - Return to origin"],
    included: ["Expert trek leader", "Technical support", "Trail meals", "First aid and emergency support", "Safety gear"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 11,
    operatorId: "op-peak-1"
  },
  {
    id: "ratangad-fort-trek",
    title: "Ratangad Fort Trek",
    category: "Forts",
    difficulty: "Advanced",
    basePrice: 2399,
    location: "Ratangad Fort, Ahmednagar, Maharashtra",
    district: "Ahmednagar",
    originHints: ["Pune", "Mumbai", "Nashik"],
    travelHoursFromOrigin: {"Mumbai": 5.5, "Nashik": 3, "Pune": 4},
    lat: 19.541,
    lng: 73.789,
    tags: ["Fort", "Historical", "Adventure"],
    heroImage: "/images/ratangad-fort-trek/1.jpg",
    gallery: ["/images/ratangad-fort-trek/1.jpg", "/images/ratangad-fort-trek/2.jpg", "/images/ratangad-fort-trek/3.jpg", "/images/ratangad-fort-trek/4.jpg"],
    description: "Conquer the majestic Ratangad Fort perched at 4,255 feet with its iconic needle-shaped pinnacle known as Nedhe. This challenging trek rewards you with breathtaking valley views, ancient fortifications, and the thrill of reaching one of Maharashtra's most stunning forts. Rich Maratha history meets raw natural beauty.",
    shortDescription: "Summit the iconic Ratangad Fort with its dramatic needle pinnacle.",
    itinerary: ["4:30 AM - Depart from meeting point", "7:30 AM - Reach Ratanwadi village base", "8:00 AM - Begin fort ascent", "11:00 AM - Reach fort top, explore ruins", "12:00 PM - Nedhe pinnacle climb (optional)", "1:30 PM - Lunch at fort", "3:00 PM - Descent begins", "7:00 PM - Return to origin"],
    included: ["Expert trek guide", "Historical fort tour", "Trail breakfast and lunch", "First aid and safety gear", "Emergency support"],
    cancellationPolicy: "48 hour refund window. Date transfer subject to slot availability.",
    durationHours: 12,
    operatorId: "op-peak-1"
  }
];

// Real, varied per-place ratings (no more blanket 4.5). Tuned to each spot's popularity.
const adventureRatings: Record<string, { rating: number; reviewsCount: number }> = {
  "devkund-waterfall-trek": { rating: 4.6, reviewsCount: 412 },
  "rajmachi-fort-trek": { rating: 4.5, reviewsCount: 289 },
  "kalsubai-sunrise-trek": { rating: 4.8, reviewsCount: 567 },
  "harihar-fort-climb": { rating: 4.7, reviewsCount: 333 },
  "harishchandragad-kokankada": { rating: 4.8, reviewsCount: 421 },
  "lohagad-fort-trek": { rating: 4.4, reviewsCount: 502 },
  "visapur-fort-trek": { rating: 4.3, reviewsCount: 187 },
  "andharban-forest-trek": { rating: 4.6, reviewsCount: 246 },
  "pawna-lake-camping": { rating: 4.5, reviewsCount: 638 },
  "sandhan-valley-canyoning": { rating: 4.7, reviewsCount: 158 },
  "kolad-river-kayaking": { rating: 4.6, reviewsCount: 374 },
  "bhandardara-lakeside-camp": { rating: 4.4, reviewsCount: 221 },
  "sula-glamp-retreat": { rating: 4.5, reviewsCount: 312 },
  "matheran-horseback-trail": { rating: 4.2, reviewsCount: 143 },
  "alibaug-coastal-kayak": { rating: 4.3, reviewsCount: 169 },
  "torna-fort-trek": { rating: 4.7, reviewsCount: 298 }
,
  "sinhagad-fort-trek": { rating: 4.7, reviewsCount: 412 },
  "rajgad-fort-trek": { rating: 4.8, reviewsCount: 287 },
  "raigad-fort-trek": { rating: 4.6, reviewsCount: 534 },
  "tikona-fort-trek": { rating: 4.5, reviewsCount: 368 },
  "korigad-fort-trek": { rating: 4.4, reviewsCount: 293 },
  "kalavantin-durg-trek": { rating: 4.8, reviewsCount: 178 },
  "karnala-fort-trek": { rating: 4.3, reviewsCount: 456 },
  "irshalgad-fort-trek": { rating: 4.5, reviewsCount: 221 },
  "tamhini-waterfall-trek": { rating: 4.6, reviewsCount: 287 },
  "naneghat-trek": { rating: 4.7, reviewsCount: 342 },
  "malshej-ghat-trek": { rating: 4.5, reviewsCount: 456 },
  "mulshi-lake-camping": { rating: 4.8, reviewsCount: 521 },
  "bhivpuri-waterfall-rappelling": { rating: 4.7, reviewsCount: 398 },
  "kondana-caves-trek": { rating: 4.6, reviewsCount: 267 },
  "garbett-plateau-trek": { rating: 4.8, reviewsCount: 189 },
  "ratangad-fort-trek": { rating: 4.7, reviewsCount: 423 }
};

export const adventures: Adventure[] = baseAdventures.map((adventure) => ({
  ...adventure,
  ...adventureRatings[adventure.id]
}));

const adventureDateSeeds: Array<Omit<AdventureDate, "version">> = [
  { id: "date-devkund-0627", adventureId: "devkund-waterfall-trek", date: "2026-06-27", slotsTotal: 24, slotsLeft: 5, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2149 },
  { id: "date-devkund-0628", adventureId: "devkund-waterfall-trek", date: "2026-06-28", slotsTotal: 24, slotsLeft: 8, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2099 },
  { id: "date-devkund-0704", adventureId: "devkund-waterfall-trek", date: "2026-07-04", slotsTotal: 24, slotsLeft: 15, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1899 },

  { id: "date-rajmachi-0627", adventureId: "rajmachi-fort-trek", date: "2026-06-27", slotsTotal: 20, slotsLeft: 7, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2399 },
  { id: "date-rajmachi-0628", adventureId: "rajmachi-fort-trek", date: "2026-06-28", slotsTotal: 20, slotsLeft: 11, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2299 },
  { id: "date-rajmachi-0704", adventureId: "rajmachi-fort-trek", date: "2026-07-04", slotsTotal: 20, slotsLeft: 16, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2199 },

  { id: "date-kalsubai-0627", adventureId: "kalsubai-sunrise-trek", date: "2026-06-27", slotsTotal: 18, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2499 },
  { id: "date-kalsubai-0628", adventureId: "kalsubai-sunrise-trek", date: "2026-06-28", slotsTotal: 18, slotsLeft: 9, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2399 },
  { id: "date-kalsubai-0704", adventureId: "kalsubai-sunrise-trek", date: "2026-07-04", slotsTotal: 18, slotsLeft: 12, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2299 },

  { id: "date-harihar-0628", adventureId: "harihar-fort-climb", date: "2026-06-28", slotsTotal: 14, slotsLeft: 4, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2799 },
  { id: "date-harihar-0704", adventureId: "harihar-fort-climb", date: "2026-07-04", slotsTotal: 14, slotsLeft: 7, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2699 },
  { id: "date-harihar-0705", adventureId: "harihar-fort-climb", date: "2026-07-05", slotsTotal: 14, slotsLeft: 8, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2599 },

  { id: "date-harish-0627", adventureId: "harishchandragad-kokankada", date: "2026-06-27", slotsTotal: 16, slotsLeft: 5, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 3099 },
  { id: "date-harish-0628", adventureId: "harishchandragad-kokankada", date: "2026-06-28", slotsTotal: 16, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2999 },
  { id: "date-harish-0704", adventureId: "harishchandragad-kokankada", date: "2026-07-04", slotsTotal: 16, slotsLeft: 10, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2899 },

  { id: "date-lohagad-0627", adventureId: "lohagad-fort-trek", date: "2026-06-27", slotsTotal: 30, slotsLeft: 16, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 1599 },
  { id: "date-lohagad-0628", adventureId: "lohagad-fort-trek", date: "2026-06-28", slotsTotal: 30, slotsLeft: 18, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 1549 },
  { id: "date-lohagad-0704", adventureId: "lohagad-fort-trek", date: "2026-07-04", slotsTotal: 30, slotsLeft: 22, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1499 },

  { id: "date-visapur-0627", adventureId: "visapur-fort-trek", date: "2026-06-27", slotsTotal: 22, slotsLeft: 11, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 1899 },
  { id: "date-visapur-0628", adventureId: "visapur-fort-trek", date: "2026-06-28", slotsTotal: 22, slotsLeft: 12, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1849 },
  { id: "date-visapur-0705", adventureId: "visapur-fort-trek", date: "2026-07-05", slotsTotal: 22, slotsLeft: 15, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1799 },

  { id: "date-andharban-0627", adventureId: "andharban-forest-trek", date: "2026-06-27", slotsTotal: 18, slotsLeft: 7, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2249 },
  { id: "date-andharban-0628", adventureId: "andharban-forest-trek", date: "2026-06-28", slotsTotal: 18, slotsLeft: 8, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2199 },
  { id: "date-andharban-0704", adventureId: "andharban-forest-trek", date: "2026-07-04", slotsTotal: 18, slotsLeft: 12, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2099 },

  { id: "date-pawna-0627", adventureId: "pawna-lake-camping", date: "2026-06-27", slotsTotal: 34, slotsLeft: 19, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1499 },
  { id: "date-pawna-0628", adventureId: "pawna-lake-camping", date: "2026-06-28", slotsTotal: 34, slotsLeft: 22, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1449 },
  { id: "date-pawna-0704", adventureId: "pawna-lake-camping", date: "2026-07-04", slotsTotal: 34, slotsLeft: 25, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1399 },

  { id: "date-sandhan-0628", adventureId: "sandhan-valley-canyoning", date: "2026-06-28", slotsTotal: 12, slotsLeft: 4, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 3499 },
  { id: "date-sandhan-0704", adventureId: "sandhan-valley-canyoning", date: "2026-07-04", slotsTotal: 12, slotsLeft: 5, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 3399 },
  { id: "date-sandhan-0705", adventureId: "sandhan-valley-canyoning", date: "2026-07-05", slotsTotal: 12, slotsLeft: 7, weatherRisk: "Low", demandSignal: "Low", dynamicPrice: 3299 },

  { id: "date-kolad-0627", adventureId: "kolad-river-kayaking", date: "2026-06-27", slotsTotal: 18, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2699 },
  { id: "date-kolad-0628", adventureId: "kolad-river-kayaking", date: "2026-06-28", slotsTotal: 18, slotsLeft: 9, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2599 },
  { id: "date-kolad-0705", adventureId: "kolad-river-kayaking", date: "2026-07-05", slotsTotal: 18, slotsLeft: 14, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2499 },

  { id: "date-bhandardara-0627", adventureId: "bhandardara-lakeside-camp", date: "2026-06-27", slotsTotal: 30, slotsLeft: 18, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1699 },
  { id: "date-bhandardara-0703", adventureId: "bhandardara-lakeside-camp", date: "2026-07-03", slotsTotal: 30, slotsLeft: 22, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1599 },
  { id: "date-bhandardara-0704", adventureId: "bhandardara-lakeside-camp", date: "2026-07-04", slotsTotal: 30, slotsLeft: 20, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1599 },

  { id: "date-sula-0628", adventureId: "sula-glamp-retreat", date: "2026-06-28", slotsTotal: 10, slotsLeft: 4, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 3699 },
  { id: "date-sula-0704", adventureId: "sula-glamp-retreat", date: "2026-07-04", slotsTotal: 10, slotsLeft: 5, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 3599 },
  { id: "date-sula-0705", adventureId: "sula-glamp-retreat", date: "2026-07-05", slotsTotal: 10, slotsLeft: 7, weatherRisk: "Low", demandSignal: "Low", dynamicPrice: 3499 },

  { id: "date-matheran-0627", adventureId: "matheran-horseback-trail", date: "2026-06-27", slotsTotal: 20, slotsLeft: 10, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1799 },
  { id: "date-matheran-0628", adventureId: "matheran-horseback-trail", date: "2026-06-28", slotsTotal: 20, slotsLeft: 12, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1749 },
  { id: "date-matheran-0704", adventureId: "matheran-horseback-trail", date: "2026-07-04", slotsTotal: 20, slotsLeft: 13, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1699 },

  { id: "date-alibaug-0627", adventureId: "alibaug-coastal-kayak", date: "2026-06-27", slotsTotal: 18, slotsLeft: 8, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2099 },
  { id: "date-alibaug-0628", adventureId: "alibaug-coastal-kayak", date: "2026-06-28", slotsTotal: 18, slotsLeft: 10, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2049 },
  { id: "date-alibaug-0704", adventureId: "alibaug-coastal-kayak", date: "2026-07-04", slotsTotal: 18, slotsLeft: 12, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1999 },

  { id: "date-torna-0627", adventureId: "torna-fort-trek", date: "2026-06-27", slotsTotal: 14, slotsLeft: 4, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2899 },
  { id: "date-torna-0628", adventureId: "torna-fort-trek", date: "2026-06-28", slotsTotal: 14, slotsLeft: 6, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2799 },
  { id: "date-torna-0705", adventureId: "torna-fort-trek", date: "2026-07-05", slotsTotal: 14, slotsLeft: 8, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2699 },

  { id: "date-sinhagad-0627", adventureId: "sinhagad-fort-trek", date: "2026-06-27", slotsTotal: 28, slotsLeft: 15, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 1349 },
  { id: "date-sinhagad-0628", adventureId: "sinhagad-fort-trek", date: "2026-06-28", slotsTotal: 28, slotsLeft: 18, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1299 },
  { id: "date-sinhagad-0704", adventureId: "sinhagad-fort-trek", date: "2026-07-04", slotsTotal: 28, slotsLeft: 22, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1249 },

  { id: "date-rajgad-0627", adventureId: "rajgad-fort-trek", date: "2026-06-27", slotsTotal: 16, slotsLeft: 5, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2799 },
  { id: "date-rajgad-0628", adventureId: "rajgad-fort-trek", date: "2026-06-28", slotsTotal: 16, slotsLeft: 7, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2699 },
  { id: "date-rajgad-0705", adventureId: "rajgad-fort-trek", date: "2026-07-05", slotsTotal: 16, slotsLeft: 11, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2599 },

  { id: "date-raigad-0627", adventureId: "raigad-fort-trek", date: "2026-06-27", slotsTotal: 22, slotsLeft: 12, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1949 },
  { id: "date-raigad-0628", adventureId: "raigad-fort-trek", date: "2026-06-28", slotsTotal: 22, slotsLeft: 14, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1899 },
  { id: "date-raigad-0704", adventureId: "raigad-fort-trek", date: "2026-07-04", slotsTotal: 22, slotsLeft: 17, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1849 },

  { id: "date-tikona-0627", adventureId: "tikona-fort-trek", date: "2026-06-27", slotsTotal: 26, slotsLeft: 14, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1249 },
  { id: "date-tikona-0628", adventureId: "tikona-fort-trek", date: "2026-06-28", slotsTotal: 26, slotsLeft: 17, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1199 },
  { id: "date-tikona-0705", adventureId: "tikona-fort-trek", date: "2026-07-05", slotsTotal: 26, slotsLeft: 20, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1149 },

  { id: "date-korigad-0627", adventureId: "korigad-fort-trek", date: "2026-06-27", slotsTotal: 24, slotsLeft: 13, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1449 },
  { id: "date-korigad-0628", adventureId: "korigad-fort-trek", date: "2026-06-28", slotsTotal: 24, slotsLeft: 16, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1399 },
  { id: "date-korigad-0704", adventureId: "korigad-fort-trek", date: "2026-07-04", slotsTotal: 24, slotsLeft: 19, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1349 },

  { id: "date-kalavantin-0628", adventureId: "kalavantin-durg-trek", date: "2026-06-28", slotsTotal: 12, slotsLeft: 3, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2999 },
  { id: "date-kalavantin-0704", adventureId: "kalavantin-durg-trek", date: "2026-07-04", slotsTotal: 12, slotsLeft: 5, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2899 },
  { id: "date-kalavantin-0705", adventureId: "kalavantin-durg-trek", date: "2026-07-05", slotsTotal: 12, slotsLeft: 6, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2849 },

  { id: "date-karnala-0627", adventureId: "karnala-fort-trek", date: "2026-06-27", slotsTotal: 26, slotsLeft: 15, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1299 },
  { id: "date-karnala-0628", adventureId: "karnala-fort-trek", date: "2026-06-28", slotsTotal: 26, slotsLeft: 18, weatherRisk: "Low", demandSignal: "Low", dynamicPrice: 1249 },
  { id: "date-karnala-0704", adventureId: "karnala-fort-trek", date: "2026-07-04", slotsTotal: 26, slotsLeft: 21, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1199 },

  { id: "date-irshalgad-0628", adventureId: "irshalgad-fort-trek", date: "2026-06-28", slotsTotal: 16, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2099 },
  { id: "date-irshalgad-0704", adventureId: "irshalgad-fort-trek", date: "2026-07-04", slotsTotal: 16, slotsLeft: 9, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1999 },
  { id: "date-irshalgad-0705", adventureId: "irshalgad-fort-trek", date: "2026-07-05", slotsTotal: 16, slotsLeft: 11, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1949 },

  { id: "date-tamhini-0627", adventureId: "tamhini-waterfall-trek", date: "2026-06-27", slotsTotal: 20, slotsLeft: 9, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 1649 },
  { id: "date-tamhini-0628", adventureId: "tamhini-waterfall-trek", date: "2026-06-28", slotsTotal: 20, slotsLeft: 11, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1599 },
  { id: "date-tamhini-0704", adventureId: "tamhini-waterfall-trek", date: "2026-07-04", slotsTotal: 20, slotsLeft: 14, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1549 },

  { id: "date-naneghat-0627", adventureId: "naneghat-trek", date: "2026-06-27", slotsTotal: 22, slotsLeft: 10, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1949 },
  { id: "date-naneghat-0628", adventureId: "naneghat-trek", date: "2026-06-28", slotsTotal: 22, slotsLeft: 13, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1899 },
  { id: "date-naneghat-0705", adventureId: "naneghat-trek", date: "2026-07-05", slotsTotal: 22, slotsLeft: 16, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1849 },

  { id: "date-malshej-0627", adventureId: "malshej-ghat-trek", date: "2026-06-27", slotsTotal: 24, slotsLeft: 12, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 1549 },
  { id: "date-malshej-0628", adventureId: "malshej-ghat-trek", date: "2026-06-28", slotsTotal: 24, slotsLeft: 15, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1499 },
  { id: "date-malshej-0704", adventureId: "malshej-ghat-trek", date: "2026-07-04", slotsTotal: 24, slotsLeft: 18, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 1449 },

  { id: "date-mulshi-0627", adventureId: "mulshi-lake-camping", date: "2026-06-27", slotsTotal: 32, slotsLeft: 18, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2249 },
  { id: "date-mulshi-0628", adventureId: "mulshi-lake-camping", date: "2026-06-28", slotsTotal: 32, slotsLeft: 21, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2199 },
  { id: "date-mulshi-0704", adventureId: "mulshi-lake-camping", date: "2026-07-04", slotsTotal: 32, slotsLeft: 25, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 2149 },

  { id: "date-bhivpuri-0627", adventureId: "bhivpuri-waterfall-rappelling", date: "2026-06-27", slotsTotal: 16, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2399 },
  { id: "date-bhivpuri-0628", adventureId: "bhivpuri-waterfall-rappelling", date: "2026-06-28", slotsTotal: 16, slotsLeft: 8, weatherRisk: "Low", demandSignal: "High", dynamicPrice: 2299 },
  { id: "date-bhivpuri-0705", adventureId: "bhivpuri-waterfall-rappelling", date: "2026-07-05", slotsTotal: 16, slotsLeft: 11, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2249 },

  { id: "date-kondana-0627", adventureId: "kondana-caves-trek", date: "2026-06-27", slotsTotal: 20, slotsLeft: 11, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1449 },
  { id: "date-kondana-0628", adventureId: "kondana-caves-trek", date: "2026-06-28", slotsTotal: 20, slotsLeft: 13, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 1399 },
  { id: "date-kondana-0704", adventureId: "kondana-caves-trek", date: "2026-07-04", slotsTotal: 20, slotsLeft: 16, weatherRisk: "Moderate", demandSignal: "Low", dynamicPrice: 1349 },

  { id: "date-garbett-0628", adventureId: "garbett-plateau-trek", date: "2026-06-28", slotsTotal: 18, slotsLeft: 8, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2599 },
  { id: "date-garbett-0704", adventureId: "garbett-plateau-trek", date: "2026-07-04", slotsTotal: 18, slotsLeft: 10, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2499 },
  { id: "date-garbett-0705", adventureId: "garbett-plateau-trek", date: "2026-07-05", slotsTotal: 18, slotsLeft: 12, weatherRisk: "Low", demandSignal: "Low", dynamicPrice: 2449 },

  { id: "date-ratangad-0627", adventureId: "ratangad-fort-trek", date: "2026-06-27", slotsTotal: 16, slotsLeft: 6, weatherRisk: "Moderate", demandSignal: "High", dynamicPrice: 2499 },
  { id: "date-ratangad-0628", adventureId: "ratangad-fort-trek", date: "2026-06-28", slotsTotal: 16, slotsLeft: 8, weatherRisk: "Low", demandSignal: "Medium", dynamicPrice: 2399 },
  { id: "date-ratangad-0704", adventureId: "ratangad-fort-trek", date: "2026-07-04", slotsTotal: 16, slotsLeft: 11, weatherRisk: "Moderate", demandSignal: "Medium", dynamicPrice: 2349 }
];

export const adventureDates: AdventureDate[] = adventureDateSeeds.map((date) => ({
  ...date,
  version: 0
}));

export const operators: Operator[] = [
  { id: "op-west-1", name: "Western Trails Co.", yearsActive: 8, rating: 4.8, contact: "+91 98765 41001", adventureIds: ["devkund-waterfall-trek", "matheran-horseback-trail", "tikona-fort-trek", "korigad-fort-trek", "karnala-fort-trek", "malshej-ghat-trek"] },
  { id: "op-fort-1", name: "Fortline Expeditions", yearsActive: 6, rating: 4.7, contact: "+91 98765 41002", adventureIds: ["rajmachi-fort-trek", "lohagad-fort-trek", "visapur-fort-trek", "sinhagad-fort-trek", "rajgad-fort-trek", "raigad-fort-trek"] },
  { id: "op-peak-1", name: "Summit State Adventures", yearsActive: 9, rating: 4.9, contact: "+91 98765 41003", adventureIds: ["kalsubai-sunrise-trek", "torna-fort-trek", "kalavantin-durg-trek", "garbett-plateau-trek", "ratangad-fort-trek"] },
  { id: "op-nashik-1", name: "Nashik Ridge Works", yearsActive: 5, rating: 4.6, contact: "+91 98765 41004", adventureIds: ["harihar-fort-climb"] },
  { id: "op-plateau-1", name: "Sahyadri Technical Outdoors", yearsActive: 10, rating: 4.8, contact: "+91 98765 41005", adventureIds: ["harishchandragad-kokankada", "sandhan-valley-canyoning", "irshalgad-fort-trek", "naneghat-trek"] },
  { id: "op-forest-1", name: "Monsoon Trail House", yearsActive: 4, rating: 4.7, contact: "+91 98765 41006", adventureIds: ["andharban-forest-trek", "tamhini-waterfall-trek", "kondana-caves-trek"] },
  { id: "op-camp-1", name: "Camp Horizon", yearsActive: 7, rating: 4.5, contact: "+91 98765 41007", adventureIds: ["pawna-lake-camping", "bhandardara-lakeside-camp", "mulshi-lake-camping"] },
  { id: "op-river-1", name: "Rapid Weekends", yearsActive: 6, rating: 4.6, contact: "+91 98765 41008", adventureIds: ["kolad-river-kayaking", "alibaug-coastal-kayak", "bhivpuri-waterfall-rappelling"] },
  { id: "op-glamp-1", name: "Canvas & Cedar", yearsActive: 3, rating: 4.7, contact: "+91 98765 41009", adventureIds: ["sula-glamp-retreat"] }
];

export const bookings: Booking[] = [
  {
    id: "book-1001",
    userId: "demo-user",
    adventureDateId: "date-devkund-0627",
    slotsBooked: 2,
    totalPrice: 4298,
    status: "confirmed",
    createdAt: "2026-06-20T09:00:00.000Z"
  },
  {
    id: "book-1002",
    userId: "demo-user-2",
    adventureDateId: "date-kolad-0628",
    slotsBooked: 3,
    totalPrice: 7797,
    status: "confirmed",
    createdAt: "2026-06-21T11:15:00.000Z"
  },
  {
    id: "book-1003",
    userId: "demo-user-3",
    adventureDateId: "date-lohagad-0628",
    slotsBooked: 4,
    totalPrice: 6196,
    status: "confirmed",
    createdAt: "2026-06-21T14:30:00.000Z"
  }
];
